### ISSUE TITLE
Service Interceptor blocks access to the webMethods Integration Server

### ISSUE THREAD

**Issue by rajamani-muniappan** [SoftwareAG/WxNewRelicAgent#2]
Hi John,

Thanks for such a wonderful idea and implementing this feature.

I am so excited to try this feature. I have copied the package and restarted the server but the service interceptor is blocking access to the server. I have noticed this even before configuring the newrelic.yml file with our license key etc. I tried to configure and restart the IS but ended up with the same issue.

**Error Message:**

_Access Denied.

Services necessary to show the Integration Server Administrator are currently unavailable on this port. This is most likely due to port security restrictions.

If this is the only port available to access the Integration Server, contact webMethods Support._

If I try to hit a REST service deployed on the server, ended up with this issue.

_java.lang.Error:Unresolved compilation problem: \n\tUnhandled exception type MalformedURLException\n_

However, I could see JVM metrics and transaction "OtherTransaction/Custom/com.jc.wm.newrelic.ServiceInterceptor/process" in NewRelic.

We have webMethods Integration Server 10.11 on AIX and Linux (tried on both platforms).

Would you be able to review this issue and suggest the fix for this? If you need additional details / if we need to jump in to a call, I will be happy to.

Thank you!

**Comment by johnpcarter** [comment]
Hi Rajamani,
Sorry to hear about your problem, can you provide me with your log files ?
I would need 

<SAG_HOME>/profiles/IS_default/logs/wrapper.log
<SAG_HOME>/IntegrationServer/instances/default/logs/server.log

Once I have that, we can perhaps organise a call unless I see something very obvious to fix the issue. My email address is john.carter@softwareag.com, for info I am based in Europe so on CET time-zone.

regards,
John.

**Comment by rajamani-muniappan** [comment]
Thanks for your quick reply. I have shared the logs to your email address john.carter@softwareag.com.

**Comment by johnpcarter** [comment]
Hi,
I just discovered that after restarting my own dev environment, I get the same error! Seems that I managed to introduce a compilation error into my last build that I only discovered on restarting. Still investigating how that happened. Can you please download the latest version and try again.

Sorry for that,
John.

**Comment by rajamani-muniappan** [comment]
Thank you, John! I will download the latest version and try again.

Additionally, here are the JVM and OS Version Details:

Java Version:
java version "11.0.14.1" 2022-02-08
IBM Semeru Runtime Certified Edition 11.0.14.1 (build 11.0.14.1+1)
Eclipse OpenJ9 VM 11.0.14.1 (build openj9-0.30.1, JRE 11 AIX ppc64-64-Bit Compressed References 20220215_254 (JIT enabled, AOT enabled)
OpenJ9   - 9dccbe076
OMR      - 56c3376ba
JCL      - f0981daedc based on jdk-11.0.14.1+1)

IBM AIX Version:
7200-05-03-2148

**Comment by rajamani-muniappan** [comment]
Here is the update - 

It worked 👍 

Encountered the below issue related to SSL certificates but resolved it by referring https://docs.newrelic.com/docs/apm/agents/java-agent/configuration/configuring-your-ssl-certificates/ 

`com.newrelic.agent.rpm.RPMConnectionServiceImpl INFO: Failed to connect to collector.newrelic.com:443 for PERF-ESB-webMethods-NRT: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`

I have tested for REST services so far. I will review the results, continue to test for other transactions such as JMS and share the feedback. 

Thanks for your quick response.

--
Rajamani Muniappan
